package tqs.covid.frontend;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
// Generated by Selenium IDE
import org.junit.jupiter.api.Test;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;


public class FrontendTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void frontendTest() {
    driver.get("http://localhost:4200/world");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    driver.findElement(By.cssSelector("tr:nth-child(6) .bi")).click();
    driver.findElement(By.cssSelector(".btn-danger")).click();
    driver.findElement(By.id("form1")).click();
    driver.findElement(By.id("form1")).sendKeys("prt");
    driver.findElement(By.cssSelector(".bi-search")).click();
    driver.findElement(By.id("form2")).click();
    driver.findElement(By.id("form2")).sendKeys("Italy");
    driver.findElement(By.cssSelector(".btn:nth-child(3)")).click();
    driver.findElement(By.id("form1")).click();
    driver.findElement(By.id("form1")).sendKeys("fra");
    driver.findElement(By.id("form2")).click();
    driver.findElement(By.id("form2")).sendKeys("France");
    driver.findElement(By.cssSelector("app-graph")).click();
    driver.findElement(By.cssSelector(".bi-search")).click();
    driver.findElement(By.cssSelector(".sidebar-item:nth-child(3) .hide-menu")).click();
  }
}
